title: Paolo Broglio Devlog
description: My development and personal blog
author: Paolo Broglio
github: https://github.com/paolobroglio
about: I'm a Computer Scientist and Software Engineer
google_analytics: UA-160185421-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/Paolo_Broglio"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/paolo-broglio-41b1b1b9/"
    - icon: fa-github
      link: "https://github.com/paolobroglio"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://paolobroglio.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
